[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Kostas Pardalis", email = "costas.pardalis@gmail.com"},
]
dependencies = [
    "duckdb>=0.7.1",
    "polars>=0.17.2",
]
requires-python = ">=3.10"
license = {text = "MIT"}
